config/routes.rb
Rails.application.routes.draw do
  root to: 'invoices#index'

  resources :invoices, :invoice_items, :articles
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many :invoice_items, dependent: :destroy
    has_many :articles, dependent: :destroy

    STATUS_CLASS = {
        :draft => "badge badge-secondary",
        :sent => "badge badge-primary",
        :paid => "badge badge-success"
    }

    def subtotal
        self.articles.map { |item| item.qty * item.price }.sum
    end

    def discount_calculated
        subtotal * (self.discount / 100.0)
    end

    def vat_calculated
        (subtotal - discount_calculated) * (self.vat / 100.0)
    end

    def total
        subtotal - discount_calculated + vat_calculated
    end

    def status_class
        STATUS_CLASS[self.status.to_sym]
    end
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @invoice = Invoice.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    byebug
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def article_params
      params.require(:article).permit(:name, :description, :price, :qty, :invoice_id)
    end

end

app/controllers/invoice_items_controller.rb
class InvoiceItemsController < ApplicationController
    def index
      @invoice_items = InvoiceItem.all
    end
    def new
      @invoice_item = InvoiceItem.new
    end
  
    def create
      #byebug
      @invoice_item = InvoiceItem.new(invoice_item_params)
  
      if @invoice_item.save
        redirect_to @invoice_item
      else
        render :new, status: :unprocessable_entity
      end
    end
   
  
    def show
      @invoice_item = InvoiceItem.find(params[:id])
  
          respond_to do |format|
              format.html
              format.pdf do
                  render pdf: "Invoice No. #{@invoice.id}",
                  page_size: 'A4',
                  template: "invoices/show.html.erb",
                  layout: "pdf.html",
                  orientation: "Landscape",
                  lowquality: true,
                  zoom: 1,
                  dpi: 75
              end
          end
    end
  
    private
          
          def invoice_item_params
            params.require(:invoice_item).permit(:name, :description, :price, :qty, :invoice_id)
          end
      
  end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    #byebug
    @invoices = scope
  end
  def new
    @invoice = Invoice.new
  end

  def create
    #byebug
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to @invoice
    else
      render :new, status: :unprocessable_entity
    end
  end



  def show
    @invoice = scope.find(params[:id])

        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice No. #{@invoice.id}",
                page_size: 'A4',
                template: "invoices/show.html.erb",
                layout: "pdf.html",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
            end
        end
  end

  private
        def scope
            ::Invoice.all.includes(:invoice_items)
        end
        def invoice_params
          params.require(:invoice).permit(:from_full_name, :from_address, :from_email, :from_phone, :to_full_name, :to_address, :to_email, 
                                           :to_phone, :status, :discount, :vat)
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Invoice Date</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.name %></td>
        <td><%= invoice.description %></td>
        <td><%= invoice.price %></td>
        <td><%= invoice.qty %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :invoice_id %><br>
    <%= form.text_field :invoice_id %>
  </div>
  <div>
    <%= form.label  :price %><br>
   <%= form.number_field  :price, in: 1.0..2000.0, step: 0.5 %>
  </div>
  <div>
    <%= form.label :qty %><br>
    <%= form.number_field :qty, in: 1.0..20.0, step: 1 %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
          <tr class="top">
            <td colspan="4">
              <table>
                <tr>
                  <td class="title">
                    <%= image_tag wicked_pdf_asset_base64('company_logo.png') %>
                  </td>

                  <td>
                    Invoice
                    <br>
                    Created: <b><%= @article.created_at.strftime('%d/%m/%Y') %></b>
                    <br>
                    Due: <b><%= (@article.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                    <br>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="information">
            <td colspan="4">
              <table>
                <tr>
                  <td>
                    <b><%= @article.name %></b><br>
                    <%= @article.description %><br>
                    <%= @article.invoice_id %><br>
                    <i class="far fa-envelope"></i> <%= @article.price %><br>
                    <i class="fas fa-phone"></i> <%= @article.qty %>
                  </td>

                  
                </tr>
              </table>
            </td>
          </tr>

          <tr class="heading">
            <td>Payment Method</td>
            <td colspan="2"></td>
            <td class="right">Cache</td>
          </tr>

          <tr class="details">
            <td>Delivery Method</td>
            <td colspan="2"></td>
            <td class="right">1000</td>
          </tr>

          <tr class="heading">
            <td>Item</td>
            <td class="right">Price</td>
            <td class="right">Qty</td>
            <td>Total</td>
          </tr>

          <% @invoice.articles.each do |invoice_item| %>
            <tr class="item">
                <td>
                    <%= invoice_item.name %><br>
                    <small><%= invoice_item.description %></small>
                </td>

                <td class="right">
                    <%= number_to_currency(invoice_item.price) %>
                </td>

                <td class="right">
                    x <%= invoice_item.qty %>
                </td>

                <td>
                    <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
                </td>
            </tr>
          <% end %>

          <tr>
            <td colspan="4"></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b></td>
            <td><%= number_to_currency(@invoice.subtotal) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Discount (<%= @invoice.discount %>%)</b></td>
            <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>VAT (<%= @invoice.vat %>%)</b></td>
            <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
          </tr>

          <tr class="heading">
            <td colspan="2"></td>
            <td><b>TOTAL:</b></td>
            <td>
               <b><%= number_to_currency(@invoice.total) %></b>
            </td>
          </tr>
        </table>
    </div>

app/views/invoice_items/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Discount (%)</th>
      <th scope="col">VAT (%)</th>
      <th scope="col">TOTAL</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoice_items.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.name %></td>
        <td><%= invoice.description %></td>
        <td><%= invoice.price %></td>
        <td><%= invoice.qty %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoice_items/new.html.erb
<h1>New Article</h1>

<%= form_with model: @invoice_item do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div> 
  <div>
    <%= form.label  :price %><br>
   <%= form.number_field  :price, in: 1.0..20000.0, step: 0.5 %>
   
  </div>
  <div>
    <%= form.label :qty %><br>
    <%= form.number_field :qty, in: 1.0..20.0, step: 1%>
  </div>
  
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_items/show.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
          <tr class="top">
            <td colspan="4">
              <table>
                <tr>
                  <td class="title">
                    <%= image_tag wicked_pdf_asset_base64('company_logo.png') %>
                  </td>

                  <td>
                    Invoice #: <b><%= @invoice.id %></b>
                    <br>
                    Created: <b><%= @invoice_item.created_at.strftime('%d/%m/%Y') %></b>
                    <br>
                    Due: <b><%= (@invoice_item.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                    <br>
                    
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="information">
            <td colspan="4">
              <table>
                <tr>
                  <td>
                    <b><%= @invoice_item.name %></b><br>
                    <%= @invoice_item.description %><br>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="heading">
            <td>Payment Method</td>
            <td colspan="2"></td>
            <td class="right">Cache</td>
          </tr>

          <tr class="details">
            <td>Delivery Method</td>
            <td colspan="2"></td>
            <td class="right">1000</td>
          </tr>

          <tr class="heading">
            <td>Item</td>
            <td class="right">Price</td>
            <td class="right">Qty</td>
            <td>Total</td>
          </tr>

          <% @invoice.invoice_items.each do |invoice_item| %>
            <tr class="item">
                <td>
                    <%= invoice_item.name %><br>
                    <small><%= invoice_item.description %></small>
                </td>

                <td class="right">
                    <%= number_to_currency(invoice_item.price) %>
                </td>

                <td class="right">
                    x <%= invoice_item.qty %>
                </td>

                <td>
                    <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
                </td>
            </tr>
          <% end %>

          <tr>
            <td colspan="4"></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b></td>
            <td><%= number_to_currency(@invoice.subtotal) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Discount (<%= @invoice.discount %>%)</b></td>
            <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>VAT (<%= @invoice.vat %>%)</b></td>
            <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
          </tr>

          <tr class="heading">
            <td colspan="2"></td>
            <td><b>TOTAL:</b></td>
            <td>
               <b><%= number_to_currency(@invoice.total) %></b>
            </td>
          </tr>
        </table>
    </div>

app/views/invoices/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Status</th>
      <th scope="col">Discount (%)</th>
      <th scope="col">VAT (%)</th>
      <th scope="col">TOTAL</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <th scope="row"><%= invoice.created_at.strftime('%d/%m/%Y') %></th>
        <td><%= invoice.from_full_name %></td>
        <td><%= invoice.to_full_name %></td>
        <td><span class="<%= invoice.status_class %>"><%= invoice.status %></span></td>
        <td><%= invoice.discount %></td>
        <td><%= invoice.vat %></td>
        <td><%= number_to_currency(invoice.total) %></td>
        <td><%= link_to 'View', invoice_path(invoice) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_with model: @invoice do |form| %>
  <div>
    <%= form.label :from_full_name %><br>
    <%= form.text_field :from_full_name %>
  </div>
  <div>
    <%= form.label :from_address %><br>
    <%= form.text_field :from_address %>
  </div>
  <div>
    <%= form.label :from_email %><br>
    <%= form.text_field :from_email %>
  </div>
  <div>
    <%= form.label :from_phone %><br>
    <%= form.text_field :from_phone %>
  </div>
  <div>
    <%= form.label :to_full_name %><br>
    <%= form.text_field :to_full_name%>
  </div>
  <div>
    <%= form.label :to_address %><br>
    <%= form.text_field :to_address %>
  </div>
  <div>
    <%= form.label :to_email %><br>
    <%= form.text_field :to_email %>
  </div>
  <div>
    <%= form.label :to_phone %><br>
    <%= form.text_field :to_phone %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.text_field :status %>
  </div>
  <div>
    <%= form.label  :discount %><br>
   <%= form.number_field  :discount, value: @invoice.discount ? '%.2f' % @invoice.discount : nil, min: 0, step: 0.01 %>
   
  </div>
  <div>
    <%= form.label :vat %><br>
    <%= form.number_field :vat, value: @invoice.vat ? '%.2f' % @invoice.vat : nil, min: 0, step: 0.01 %>
  </div>
    
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/show.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
          <tr class="top">
            <td colspan="4">
              <table>
                <tr>
                  <td class="title">
                    <%= image_tag wicked_pdf_asset_base64('company_logo.png') %>
                  </td>

                  <td>
                    Invoice #: <b><%= @invoice.id %></b>
                    <br>
                    Created: <b><%= @invoice.created_at.strftime('%d/%m/%Y') %></b>
                    <br>
                    Due: <b><%= (@invoice.created_at + 1.month).strftime('%d/%m/%Y') %></b>
                    <br>
                    Status: <span class="<%= @invoice.status_class %>"><%= @invoice.status %></span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="information">
            <td colspan="4">
              <table>
                <tr>
                  <td>
                    <b><%= @invoice.from_full_name %></b><br>
                    <%= @invoice.from_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.from_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.from_phone %>
                  </td>

                  <td>
                    <b><%= @invoice.to_full_name %></b><br>
                    <%= @invoice.to_address %><br>
                    <i class="far fa-envelope"></i> <%= @invoice.to_email %><br>
                    <i class="fas fa-phone"></i> <%= @invoice.to_phone %>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <tr class="heading">
            <td>Payment Method</td>
            <td colspan="2"></td>
            <td class="right">Cache</td>
          </tr>

          <tr class="details">
            <td>Delivery Method</td>
            <td colspan="2"></td>
            <td class="right">1000</td>
          </tr>

          <tr class="heading">
            <td>Item</td>
            <td class="right">Price</td>
            <td class="right">Qty</td>
            <td>Total</td>
          </tr>

          <% @invoice.invoice_items.each do |invoice_item| %>
            <tr class="item">
                <td>
                    <%= invoice_item.name %><br>
                    <small><%= invoice_item.description %></small>
                </td>

                <td class="right">
                    <%= number_to_currency(invoice_item.price) %>
                </td>

                <td class="right">
                    x <%= invoice_item.qty %>
                </td>

                <td>
                    <%= number_to_currency(invoice_item.price * invoice_item.qty) %>
                </td>
            </tr>
          <% end %>

          <tr>
            <td colspan="4"></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Subtotal</b></td>
            <td><%= number_to_currency(@invoice.subtotal) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>Discount (<%= @invoice.discount %>%)</b></td>
            <td>- <%= number_to_currency(@invoice.discount_calculated) %></td>
          </tr>

          <tr>
            <td colspan="2"></td>
            <td><b>VAT (<%= @invoice.vat %>%)</b></td>
            <td>+ <%= number_to_currency(@invoice.vat_calculated) %></td>
          </tr>

          <tr class="heading">
            <td colspan="2"></td>
            <td><b>TOTAL:</b></td>
            <td>
               <b><%= number_to_currency(@invoice.total) %></b>
            </td>
          </tr>
        </table>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeneratePdf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/shared/header" %>
  <div class="container mt-3">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "invoice" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="far fa-file-pdf"></i>
        <span class="m-l-2">Rails Generate PDFs</span>
      <% end %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      </ul>

      <% if action_name.to_sym == :show %>
        <%= link_to 'Back', root_path, class: "btn btn-outline-secondary mx-2" %>
        <%= link_to 'DOWNLOAD PDF', invoice_path(::Invoice.find(params[:id]), format: :pdf), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

    </div>
  </div>
</nav>